version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "junction-server"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-107782z28x3dv"
s3_prefix = "junction-server"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
